---

workspace_dir: "~/workspace"
vscode_sync_token: "TOKEN_ID"
vscode_sync_gist: "GIST_ID"
dotfiles_path: "~/workspace/dotfiles"

# package config
nvm_home: "~/.nvm"
init_nvm: ". {{ nvm_home }}/nvm.sh"
rbenv_home: "~/.rbenv"
ruby_version: "2.6.1"
