---

- name: Install global Pip packages
  pip:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    executable: "{{ item.executable | default(omit) }}"
  with_items: "{{ pip_packages }}"

- name: install ruby
  shell: rbenv install "{{ item }}"
  args:
    executable: /bin/bash
  ignore_errors: yes
  with_items: "{{ ruby_versions }}"

- name: rehash
  shell: rbenv rehash

- name: set global ruby version
  shell: rbenv global "{{ default_ruby_version }}"

- name: install bundler
  gem:
    name: bundler
    state: latest
    executable: ~/.rbenv/shims/gem
