---

- name: debug through ansible.env
  debug: var=ansible_env.HOME

- name: Ensure homebrew is updated
  homebrew:
    state: latest
    update_homebrew: true

- name: Tap Homebrew Bundle
  homebrew_tap:
    name: "homebrew/bundle"

- name: brew bundle
  command: brew bundle --file=files/Brewfile

- name: brew bundle clean
  command: brew bundle cleanup --file=files/Brewfile

- name: Cleanup homebrew packages
  command: brew cleanup
