---

- name: Ensure homebrew is updated
  homebrew:
    state: latest
    update_homebrew: yes

- name: Tap homebrew caskroom/cask
  homebrew_tap:
    name: "caskroom/cask"

- name: Install homebrew applications
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items: "{{ brew_packages }}"

- name: Install homebrew cask applications
  homebrew_cask:
    name: "{{ item }}"
    state: present
    install_options: "appdir=/Applications"
  with_items: "{{ cask_packages }}"

- name: Cleanup homebrew packages
  shell: brew cleanup

- name: Cleanup homebrew cask packages
  shell: brew cask cleanup
