---

- name: Create Workspace Folder
  file:
    path: "{{ workspace_dir }}"
    recurse: true
    state: directory

- name: clone my dotfiles
  git:
    repo: https://github.com/leonardocouy/dotfiles
    dest: "{{ dotfiles_path }}"

- name: execute dotfiles setup.sh
  shell: "{{ dotfiles_path }}/setup.sh"
  args:
    chdir: "{{ dotfiles_path }}"

- name: "Ensure ~/.config/karabiner directory present"
  file:
    path: ~/.config/karabiner
    state: directory

- name: "Copy karabiner.json to ~/.config/karabiner"
  copy:
    src: "{{ dotfiles_path }}/karabiner.json"
    dest: ~/.config/karabiner/karabiner.json

- name: Ensure that Spectacle directory exists
  file:
    path: "~/Library/Application\ Support/Spectacle"
    state: directory
    mode: 0755

- name: Configures Spectacle
  copy:
    src: "{{ dotfiles_path }}/spectacle.json"
    dest: "~/Library/Application\ Support/Spectacle/Shortcuts.json"

- name: Install VSCode Sync Extesnion
  command: code --install-extension Shan.code-settings-sync
  register: vscode_result
  changed_when: "'already installed' not in vscode_result.stdout"

- name: Update vscode settings sync config json
  json_module:
    path: ~/Library/Application Support/Code/User/syncLocalSettings.json
    changes:
      - type: "set"
        path: "token"
        value: "{{ vscode_sync_token }}"

- name: Update vscode settings sync gist
  json_module:
    path: ~/Library/Application Support/Code/User/settings.json
    changes:
      - type: "set"
        path: "sync.gist"
        value: "{{ vscode_sync_gist }}"

- name: Setup MacOS settings
  shell: "{{ dotfiles_path }}/.macos"

- name: Check for oh-my-zsh
  stat:
    path: ~/.oh-my-zsh
  register: stat_oh_my_zsh_result

- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: not stat_oh_my_zsh_result.stat.exists
