---

- name: clone my dotfiles
  git:
    repo: https://github.com/leonardocouy/dotfiles
    dest: "{{ dotfiles_path }}"
    version: "update-dotfiles"

- name: execute dotfiles setup.sh
  shell: "{{ dotfiles_path }}/setup.sh"

- name: copy gitconfig to ~
  copy:
    src: "{{ dotfiles_path }}/.gitconfig"
    dest: ~/.gitconfig

- name: copy gitignore_global to ~
  copy:
    src: "{{ dotfiles_path }}/.gitignore-global"
    dest: ~/.gitignore_global

- name: copy tmux conf to ~
  copy:
    src: "{{ dotfiles_path }}/.tmux.conf"
    dest: ~/.tmux.conf

- name: "Ensure ~/.config/karabiner directory present"
  file:
    path: ~/.config/karabiner
    state: directory

- name: "Copy karabiner.json to ~/.config/karabiner"
  copy:
    src: "{{ dotfiles_path }}/karabiner.json"
    dest: ~/.config/karabiner/karabiner.json

- name: Ensure that Spectacle directory exists
  file:
    path: "~/Library/Application\ Support/Spectacle"
    state: directory
    mode: 0755

- name: Configures Spectacle
  copy:
    src: "{{ dotfiles_path }}/spectacle.json"
    dest: "~/Library/Application\ Support/Spectacle/Shortcuts.json"

- name: Install VSCode Sync Extesnion
  command: code --install-extension Shan.code-settings-sync
  register: vscode_result
  changed_when: "'already installed' not in vscode_result.stdout"

- name: Update vscode settings sync config json
  json_module:
    path: ~/Library/Application Support/Code/User/syncLocalSettings.json
    changes:
      - type: "set"
        path: "token"
        value: "{{ vscode_sync_token }}"

- name: Update vscode settings sync gist
  json_module:
    path: ~/Library/Application Support/Code/User/settings.json
    changes:
      - type: "set"
        path: "sync.gist"
        value: "{{ vscode_sync_gist }}"

- name: Create Workspace Folder
  file:
   path: "{{ workspace_dir }}"
   recurse: yes
   state: directory
