---

- name: copy gitconfig
  template: 
    src: gitconfig.j2 
    dest: "~/.gitconfig"

- name: copy gitignore_global
  template: 
    src: gitignore_global.j2
    dest: ~/.gitignore_global

- name: Create Workspace Folder
  file: 
   path: "{{ workspace_dir }}"
   recurse: yes
   state: directory