---

name: playbook tests

'on':
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 5 * * 4"

jobs:
  tests:
    name: Tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        run: |
          sudo ./tests/uninstall-homebrew.sh
          sudo rm -rf /Applications/Firefox.app
          sudo rm -rf /Applications/Google\ Chrome.app
          sudo pip3 install ansible
          cp test/ansible.cfg ./ansible.cfg
          cp test/inventory ./inventory

      - name: Syntax check
        run: ansible-playbook setup.yml --syntax-check

      - name: Test playbook
        run: ansible-playbook setup.yml -vvvv
        env:
          ANSIBLE_FORCE_COLOR: '1'

      - name: Idempotence check
        run: |
          idempotence=$(mktemp)
          ansible-playbook setup.yml -vvvv | tee -a ${idempotence}
          tail ${idempotence} | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
        env:
          ANSIBLE_FORCE_COLOR: '1'
